version: "3"

services:
  api:
    restart: always
    container_name: verloop_api
    command: "python app.py"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    build:
      context: .
    ports:
      - "5000:5000"